name: ${project.name}
version: ${build.number}
description: ${project.description}
author: md_5
website: ${project.url}

main: com.md_5.swcensor.Censor

commands:
  age:
    description: View and set information about your age
